name: General Issue
description: Something else - not a bug or feature request
labels: ['triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create this issue!

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What type of issue is this?
      options:
        - Documentation
        - Question
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your issue in detail.
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
